### ISSUE TITLE
一个关于奖励函数的小问题

### ISSUE THREAD

**Issue by rokey0001** [XinJingHao/SAC-Discrete-Pytorch#2]
![屏幕截图 2024-03-19 115652](https://github.com/XinJingHao/SAC-Discrete-Pytorch/assets/59966592/279c26a8-10b6-4e61-bc52-66b42cd0ecf6)
你好作者大大，想问下这块为什么total_score需要除以一个turns

**Comment by XinJingHao** [comment]
因为重复评估了turns次，除以turns相当于获得平均分值

**Comment by rokey0001** [comment]
懂辽懂辽，谢谢，我看的太不认真了
